# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: 🧱 Build And Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  inputs: {}
  outputs:
      artifact_name:
        value: "build-artifact.tar.gz"
        description: "Artifact containing the built project"

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
    - name: Archive Build
      run: tar czf build.tar.gz .build

    - name: Publish Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: build-artifact.tar.gz
        path: .build
        retention-days: 1
